//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardaGroup.Web.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardaGroup.Web.Globalization.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于华尔达 的本地化字符串。
        /// </summary>
        public static string AboutHarda {
            get {
                return ResourceManager.GetString("AboutHarda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能制造 的本地化字符串。
        /// </summary>
        public static string AdvancedManufacturing {
            get {
                return ResourceManager.GetString("AdvancedManufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系我们 的本地化字符串。
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入华尔达 的本地化字符串。
        /// </summary>
        public static string JoinHarda {
            get {
                return ResourceManager.GetString("JoinHarda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件产品 的本地化字符串。
        /// </summary>
        public static string PartsAndModules {
            get {
                return ResourceManager.GetString("PartsAndModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卫浴产品 的本地化字符串。
        /// </summary>
        public static string PlumbingProducts {
            get {
                return ResourceManager.GetString("PlumbingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体资讯 的本地化字符串。
        /// </summary>
        public static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 研发 的本地化字符串。
        /// </summary>
        public static string ResearchAndDevelopment {
            get {
                return ResourceManager.GetString("ResearchAndDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能产品以及创新电子产品 的本地化字符串。
        /// </summary>
        public static string SmartAndInnovativeProducts {
            get {
                return ResourceManager.GetString("SmartAndInnovativeProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解决方案 的本地化字符串。
        /// </summary>
        public static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创新创业 的本地化字符串。
        /// </summary>
        public static string VentureSupport {
            get {
                return ResourceManager.GetString("VentureSupport", resourceCulture);
            }
        }
    }
}
